let name1="IQ INDIA"
document.write(`<center><h1>JAVASCRIPT</h1></center>`)
document.write(`<center><h1>${name1}</h1></center>`)
document.write(`<hr>`)
console.log(name1)


let num1=56
let num2=70
let res=num1+num2
document.write(`<h1"> <span style="color:green">${num1}</spam> +${num2} = ${res}</h1>`)
console.log(res)


let n1=Number(prompt("ENTER YUOR NUMBER 1 : "))
let n2=Number(prompt("ENTER YUOR NUMBER 2 : "))
let total=n1+n2
document.write(`Result : ${total}`)